version: 2.1

orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.0.1


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Tests
          command: pytest
      - run:
          name: Linting
          command: flake8
  build-and-push-dockerhub:
    docker:
      - image : cimg/python:3.10.2
    steps:
      - checkout 
      - setup_remote_docker: 
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Docker image
          command: docker build -t oc_lettings .
      - run:
          name: Login to DockerHub
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Link to DockerHub
          command: docker tag oc_lettings $DOCKERHUB_USERNAME/oc_lettings:$CIRCLE_SHA1
      - run:
          name: push Docker image
          command: docker push $DOCKERHUB_USERNAME/oc_lettings:$CIRCLE_SHA1

  push-heroku:
    machine: true
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: curl https://cli-assets.heroku.com/install.sh | sh 
      - run:
          name: Build Docker image to Heroku
          command: |
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push --app $HEROKU_APP_NAME web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -app $HEROKU_APP_NAME web

workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
      - build-and-push-dockerhub:
          filters:
            branches:
              only: main
          requires:
            - build-and-test
      - push-heroku:
          filters:
            branches:
              only: main
          requires:
            - build-and-push-dockerhub