version: 2.1

orbs:
  python: circleci/python@2.1.1
  heroku: circleci/heroku@2.0.0


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Tests
          command: pytest
      - run:
          name: Linting
          command: flake8

  build-and-push-dockerhub:
    docker:
      - image : cimg/python:3.10
    steps:
      - checkout 
      - setup_remote_docker: 
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Docker image
          command: docker build -t $DOCKER_IMAGE:latest .
      - run:
          name: Login to DockerHub
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Link to DockerHub
          command: docker tag $DOCKER_IMAGE:latest $DOCKERHUB_USERNAME/lettings:$CIRCLE_SHA1
      - run:
          name: push Docker image
          command: docker push $DOCKERHUB_USERNAME/lettings:$CIRCLE_SHA1


  deploy_on_heroku:
    docker:
      - image: cimg/python:3.10
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Login to DockerHub
          command: docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD

      - run:
          name: Install Heroku CLI
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
            echo $HEROKU_API_KEY
            echo $HEROKU_APP_NAME
      - run:
          name: Build and push Docker image to Heroku
          command: |
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a $HEROKU_APP_NAME web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a $HEROKU_APP_NAME web

workflows:
  sample: 
    jobs:
      - build-and-test
      - build-and-push-dockerhub:
          filters:
            branches:
              only: main
          requires:
            - build-and-test
      - deploy_on_heroku:
          filters:
            branches:
              only: main
          requires:
            - build-and-push-dockerhub