version: 2.1

orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@2.0.0


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Tests
          command: pytest
      - run:
          name: Linting
          command: flake8


  build-and-push-dockerhub:
    docker:
      - image : cimg/python:3.10
    steps:
      - checkout 
      - setup_remote_docker: 
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Docker image
          command: docker build -t $DOCKER_IMAGE .
      - run:
          name: Login to DockerHub
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Link to DockerHub
          command: docker tag $DOCKER_IMAGE $DOCKERHUB_USERNAME/lettings:$CIRCLE_SHA1
      - run:
          name: push Docker image
          command: docker push $DOCKERHUB_USERNAME/lettings:$CIRCLE_SHA1


  deploy:
    docker:
      - image: cimg/python:3.10.4
    executor: heroku/default
    steps:
       - checkout
       - heroku/install

       - run:
           name: Deploy Main to Heroku
           command: |
             HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set SECRET_KEY=$SECRET_KEY --app ${HEROKU_APP_NAME}
             HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set SENTRY_KEy=$SENTRY_KEY --app ${HEROKU_APP_NAME}
       - heroku/deploy-via-git




workflows:
  sample: 
    jobs:
      - build-and-test
      - build-and-push-dockerhub:
          filters:
            branches:
              only: main
          requires:
            - build-and-test
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - build-and-push-dockerhub