version: 2.1

orbs:
  python: circleci/python@1.5.0


jobs:
  build-and-test
    docker :
      - image: cimg/python:3.10.4
    working_directory: ~/project
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Tests
          command: pytest
      - run:
          name: Linting
          command: flake8


workflows:
  sample:
    jobs:
      - build-and-test

